### ISSUE TITLE
CG2 / Threonine

### ISSUE THREAD

**Issue by sandro-peptone** [feiglab/idpgan#2]
Is CG2 in threonine the position of the CA atom? why is it not called CG ?
Thank you! 

sandro

**Comment by feiglab** [comment]
All of the output from idpGAN should have atoms named 'CG' and those correspond to the CA positions.

I suspect that the CG2 name came from a conversion tool that automatically corrects the CG name for Threonine to CG2 (the common name used for Threonine C-gamma) assuming that it is Cgamma.

**Comment by sandro-peptone** [comment]
Great thanks! While all other CG atoms are CA, right? 
I am asking as I would like to convert the CA trace to all-atom representation using e.g. https://github.com/huhlim/cg2all

**Comment by giacomo-janson** [comment]
> Is CG2 in threonine the position of the CA atom? why is it not called CG ? Thank you!
> 
> sandro

Hello,

which PDB file and which threonine are you referring to?
Best

Giacomo

**Comment by giacomo-janson** [comment]
> Is CG2 in threonine the position of the CA atom? why is it not called CG ? Thank you!
> 
> sandro

I incidentally found out that MDTraj automatically changes to "CG2" the "CG" label of threonine beads in the PDB files we use in this repository (see idpgan/data/protan.pdb for example). These labels are stored in the "name" attribute of Atom objects from MDTraj. This is something that MDTraj does internally and does not affect the working of the idpGAN network.
